import { useState, useCallback } from 'react';
import type { GeneratedDocuments, Document, AgentTeam, InterviewAnswers } from '@/types';

function generateMasterContext(answers: InterviewAnswers, team: AgentTeam): string {
	return `╔══════════════════════════════════════════════════╗
║  MASTER PROJECT CONTEXT                         ║
║  Version: 1.0                                    ║
║  Generated by AppArchitect                       ║
╚══════════════════════════════════════════════════╝

──────────────────────────────────────────────────
SECTION 1: APP OVERVIEW
──────────────────────────────────────────────────

VISION STATEMENT:
${answers.appDescription || '[USER-UNSPECIFIED]'}

PROBLEM SOLVED:
${answers.problemSolved || '[USER-UNSPECIFIED]'}

BUSINESS TYPE: ${answers.businessType || '[USER-UNSPECIFIED]'}

──────────────────────────────────────────────────
SECTION 2: TARGET USER PERSONA
──────────────────────────────────────────────────

PRIMARY USER: ${answers.primaryUser || '[USER-UNSPECIFIED]'}

USER ROLES:
${answers.userRoles || 'Standard user role only'}

ROLE PERMISSIONS:
${answers.rolePermissions || 'Full access for authenticated users'}

──────────────────────────────────────────────────
SECTION 3: PLATFORM TARGETS
──────────────────────────────────────────────────

PLATFORMS: ${Array.isArray(answers.platforms) ? answers.platforms.join(', ') : (answers.platforms || 'Web')}

EXPECTED SCALE: ${answers.expectedScale || 'thousands'} of users at launch

COMPLIANCE REQUIREMENTS:
${Array.isArray(answers.complianceRequirements) ? answers.complianceRequirements.join(', ') : (answers.complianceRequirements || 'None')}

──────────────────────────────────────────────────
SECTION 4: CORE FEATURES
──────────────────────────────────────────────────

MVP FEATURES:
${answers.coreFeatures || '[USER-UNSPECIFIED]'}

NICE-TO-HAVE:
${answers.niceToHave || 'None specified'}

OUT OF SCOPE:
${answers.outOfScope || 'None specified'}

──────────────────────────────────────────────────
SECTION 5: TECHNICAL CAPABILITIES
──────────────────────────────────────────────────

AUTHENTICATION: ${answers.hasAuth ? 'Required' : 'Not required'}
PAYMENTS: ${answers.hasPayments ? 'Required' : 'Not required'}
REAL-TIME: ${answers.hasRealtime ? 'Required' : 'Not required'}

EXTERNAL INTEGRATIONS:
${answers.externalIntegrations || 'None specified'}

TECH STACK PREFERENCE:
${answers.techStackPreference || '[RECOMMENDED DEFAULT WILL BE APPLIED]'}

──────────────────────────────────────────────────
SECTION 6: AGENT TEAM
──────────────────────────────────────────────────

TEAM COMPOSITION: ${team.agents.length} agents

${team.agents.map((agent) => `• ${agent.designation}: ${agent.name}
  Role: ${agent.role}`).join('\n\n')}

──────────────────────────────────────────────────
SECTION 7: BUSINESS CONTEXT
──────────────────────────────────────────────────

MONETIZATION: ${answers.monetizationModel || '[USER-UNSPECIFIED]'}
LAUNCH TIMELINE: ${answers.launchTimeline || '[USER-UNSPECIFIED]'}
BRAND ASSETS: ${answers.hasBrandAssets || 'Unknown'}

──────────────────────────────────────────────────
END OF MASTER CONTEXT
──────────────────────────────────────────────────
`;
}

function generateAgentPRD(agent: { type: string; name: string; designation: string; role: string }): string {
	return `╔══════════════════════════════════════════════════╗
║  AGENT PRD — ${agent.name.toUpperCase().padEnd(35)}║
║  ${agent.designation.padEnd(47)}║
║  Version: 1.0                                    ║
╚══════════════════════════════════════════════════╝

──────────────────────────────────────────────────
SECTION 1: ROLE DECLARATION
──────────────────────────────────────────────────

AGENT NAME: ${agent.name}
DESIGNATION: ${agent.designation}

ROLE SUMMARY:
${agent.role}

PRIMARY OWNERSHIP DOMAIN:
This agent owns all tasks related to ${agent.type} functionality.

EXPLICIT EXCLUSIONS:
- This agent does NOT handle tasks outside its domain
- This agent does NOT make unilateral architectural decisions
- This agent does NOT bypass the Orchestrator for cross-agent work

──────────────────────────────────────────────────
SECTION 2: CONTEXT REFERENCE
──────────────────────────────────────────────────

MASTER CONTEXT: See Master Project Context v1.0

SECTIONS TO INTERNALIZE BEFORE BEGINNING:
• Section 1: App Overview
• Section 3: Platform Targets
• Section 4: Core Features
• Section 5: Technical Capabilities

PROJECT-LEVEL DECISIONS NOT TO OVERRIDE:
• Tech stack decisions are final
• Platform targets are fixed
• Security requirements are non-negotiable

──────────────────────────────────────────────────
SECTION 3: TECH STACK & TOOLING
──────────────────────────────────────────────────

[To be populated based on project tech stack]

──────────────────────────────────────────────────
SECTION 4: TASK LIST
──────────────────────────────────────────────────

[Tasks to be derived from Core Features]

──────────────────────────────────────────────────
SECTION 5: COLLABORATION MAP
──────────────────────────────────────────────────

COLLABORATES WITH:
• Orchestrator Agent: Task sequencing and approval gates
• QA Agent: Quality validation before phase completion

[Additional collaborations to be mapped based on team composition]

──────────────────────────────────────────────────
SECTION 6: DO'S AND DON'TS
──────────────────────────────────────────────────

DO:
✓ Follow the Master Project Context exactly
✓ Signal completion to Orchestrator before proceeding
✓ Document all decisions with rationale
✓ Write tests for all code produced
✓ Request clarification when requirements are ambiguous
✓ Follow established code style and conventions
✓ Keep commits atomic and well-documented
✓ Log progress at defined checkpoints
✓ Validate inputs before processing
✓ Handle errors gracefully with clear messages

DON'T:
✗ Make unilateral decisions on shared concerns
✗ Skip the Orchestrator for cross-agent coordination
✗ Assume context not explicitly provided
✗ Leave tasks in an incomplete state
✗ Ignore test failures
✗ Bypass code review processes
✗ Introduce dependencies without approval
✗ Deviate from agreed tech stack
✗ Merge without QA approval
✗ Hardcode configuration values

──────────────────────────────────────────────────
SECTION 7: ERROR HANDLING & ESCALATION
──────────────────────────────────────────────────

BLOCKED TASKS:
1. Pause current task
2. Document blocker with context
3. Escalate to Orchestrator Agent
4. Await resolution before resuming

UNCLEAR REQUIREMENTS:
1. Flag requirement as ambiguous
2. Propose interpretation with rationale
3. Request confirmation from Orchestrator
4. Proceed only after written confirmation

ESCALATION PATH:
This Agent → Orchestrator Agent

ESCALATION PAYLOAD FORMAT:
{
  "from": "${agent.designation}",
  "type": "ESCALATION",
  "severity": "P0" | "P1" | "P2",
  "blocker_description": "[clear description]",
  "attempted_resolution": "[what was tried]",
  "requested_action": "[specific ask]"
}

──────────────────────────────────────────────────
SECTION 8: OUTPUT & DELIVERY STANDARDS
──────────────────────────────────────────────────

DEFINITION OF DONE:
☐ All assigned tasks completed
☐ All tests passing
☐ Code reviewed and approved
☐ Documentation updated
☐ QA Agent signoff received
☐ Orchestrator notified of completion

HANDOFF CHECKLIST:
☐ Deliverables committed to repository
☐ PR created with clear description
☐ All CI checks passing
☐ Blocking dependencies resolved
☐ Next agent notified (if applicable)

──────────────────────────────────────────────────
END OF AGENT PRD
──────────────────────────────────────────────────
`;
}

function generateCollaborationMap(team: AgentTeam): string {
	let content = `╔══════════════════════════════════════════════════╗
║  COLLABORATION MAP                               ║
║  Inter-Agent Interaction Protocols               ║
║  Version: 1.0                                    ║
╚══════════════════════════════════════════════════╝

TOTAL INTERACTIONS: ${team.connections.length}

`;

	team.connections.forEach((conn) => {
		const fromAgent = team.agents.find((a) => a.id === conn.from);
		const toAgent = team.agents.find((a) => a.id === conn.to);
		if (!fromAgent || !toAgent) return;

		content += `──────────────────────────────────────────────────
INTERACTION: ${conn.interactionId}
──────────────────────────────────────────────────

AGENTS INVOLVED:
  ${fromAgent.designation} (${fromAgent.name})
  → ${toAgent.designation} (${toAgent.name})

INTERACTION TYPE: ${conn.label}

TRIGGER CONDITION:
[To be defined based on specific task dependencies]

PAYLOAD FORMAT:
{
  "interaction_id": "${conn.interactionId}",
  "from": "${fromAgent.designation}",
  "to": "${toAgent.designation}",
  "type": "${conn.label.toUpperCase().replace(/\s/g, '_')}",
  "data": { /* specific payload */ },
  "timestamp": "ISO-8601"
}

CONFIRMATION FORMAT:
{
  "interaction_id": "${conn.interactionId}",
  "status": "RECEIVED" | "PROCESSING" | "COMPLETE" | "FAILED",
  "response_data": { /* if applicable */ },
  "timestamp": "ISO-8601"
}

`;
	});

	content += `──────────────────────────────────────────────────
END OF COLLABORATION MAP
──────────────────────────────────────────────────
`;

	return content;
}

function generateSetupGuide(team: AgentTeam): string {
	return `╔══════════════════════════════════════════════════╗
║  USER SETUP & EXECUTION GUIDE                    ║
║  Step-by-Step Implementation Instructions        ║
║  Version: 1.0                                    ║
╚══════════════════════════════════════════════════╝

──────────────────────────────────────────────────
SECTION 1: PROJECT SUMMARY
──────────────────────────────────────────────────

AGENT TEAM: ${team.agents.length} specialized agents

TEAM MEMBERS:
${team.agents.map((a) => `• ${a.designation}: ${a.name}`).join('\n')}

──────────────────────────────────────────────────
SECTION 2: PREREQUISITES
──────────────────────────────────────────────────

ACCOUNTS TO CREATE:
☐ GitHub (github.com)
☐ AI Platform account (Claude, ChatGPT, or similar)
☐ Hosting provider (Vercel, Railway, etc.)
☐ Database provider (if applicable)

SOFTWARE TO INSTALL:
☐ Node.js v18+ (nodejs.org)
☐ Git (git-scm.com)
☐ Code editor (VS Code recommended)

ESTIMATED SETUP TIME: 1-2 hours

──────────────────────────────────────────────────
SECTION 3: EXECUTION SEQUENCE
──────────────────────────────────────────────────

PHASE 0: FOUNDATION
──────────────────

☐ Step 1: Initialize repository
  $ mkdir project-name && cd project-name
  $ git init

☐ Step 2: Configure environment
  Create .env file with required variables

☐ Step 3: Start Orchestrator Agent
  • Open your AI platform
  • Load the Master Project Context
  • Load the Orchestrator Agent PRD
  • Instruct: "Begin orchestration. Generate execution plan."

☐ Step 4: Orchestrator generates build order
  Wait for Orchestrator to produce sequenced task list

PHASE 1: INFRASTRUCTURE
──────────────────────

☐ Step 5: Start Database Agent (if applicable)
  • Load Database Agent PRD
  • Instruct: "Create database schema per Master Context."

☐ Step 6: Database Agent delivers schema
  • Review migrations
  • Approve and run migrations

PHASE 2: BACKEND
───────────────

☐ Step 7: Start Backend Agent
  • Load Backend Agent PRD
  • Instruct: "Scaffold API per Master Context."

☐ Step 8: Backend Agent delivers API
  • Review endpoints
  • Run tests

PHASE 3: FRONTEND
────────────────

☐ Step 9: Start Frontend Agent
  • Load Frontend Agent PRD
  • Instruct: "Build UI per Master Context."

☐ Step 10: Frontend Agent delivers UI
  • Review components
  • Run visual tests

PHASE 4: INTEGRATION & QA
────────────────────────

☐ Step 11: Start QA Agent
  • Load QA Agent PRD
  • Instruct: "Execute full test suite."

☐ Step 12: Fix any failures
  Route bugs to owning agents

PHASE 5: DEPLOYMENT
──────────────────

☐ Step 13: Start DevOps Agent
  • Load DevOps Agent PRD
  • Instruct: "Configure deployment pipeline."

☐ Step 14: Deploy to staging
  • Verify staging environment
  • Run smoke tests

☐ Step 15: Deploy to production
  • Final approval from Orchestrator
  • Ship it!

──────────────────────────────────────────────────
END OF SETUP GUIDE
──────────────────────────────────────────────────
`;
}

export function useDocumentGenerator() {
	const [documents, setDocuments] = useState<GeneratedDocuments>({
		masterContext: null,
		agentPRDs: [],
		collaborationMap: null,
		setupGuide: null,
	});
	const [isGenerating, setIsGenerating] = useState(false);

	const generateDocuments = useCallback((answers: InterviewAnswers, team: AgentTeam) => {
		setIsGenerating(true);

		// Simulate generation with streaming effect
		setTimeout(() => {
			const masterContext: Document = {
				id: 'master-context',
				type: 'master',
				title: 'Master Project Context',
				subtitle: 'Shared knowledge base for all agents',
				content: generateMasterContext(answers, team),
				generatedAt: new Date(),
			};

			const agentPRDs: Document[] = team.agents.map((agent) => ({
				id: `prd-${agent.id}`,
				type: 'agent' as const,
				title: `Agent PRD: ${agent.name}`,
				subtitle: agent.designation,
				agentId: agent.id,
				content: generateAgentPRD(agent),
				generatedAt: new Date(),
			}));

			const collaborationMap: Document = {
				id: 'collaboration-map',
				type: 'collaboration',
				title: 'Collaboration Map',
				subtitle: 'Inter-agent interaction protocols',
				content: generateCollaborationMap(team),
				generatedAt: new Date(),
			};

			const setupGuide: Document = {
				id: 'setup-guide',
				type: 'setup',
				title: 'User Setup & Execution Guide',
				subtitle: 'Step-by-step implementation instructions',
				content: generateSetupGuide(team),
				generatedAt: new Date(),
			};

			setDocuments({
				masterContext,
				agentPRDs,
				collaborationMap,
				setupGuide,
			});
			setIsGenerating(false);
		}, 3000);
	}, []);

	return {
		documents,
		isGenerating,
		generateDocuments,
	};
}
