import { useState } from 'react';
import { Download, FileText, FileDown, File, ChevronDown, Loader2, CheckCircle, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import type { GeneratedDocuments } from '@/types';
import {
  exportSuite,
  convertFromLegacyFormat,
  downloadFile,
  openPrintWindow,
  type V2PRDSuite,
  type ExportFormat as V2ExportFormat } from
'@/lib/export-utils';

interface ExportMenuProps {
  documents: GeneratedDocuments;
  projectName?: string;
  v2Suite?: V2PRDSuite | null;
  validationScore?: number;
}

type ExportFormat = 'markdown' | 'pdf' | 'docx' | 'json' | 'html';

function getAllDocumentsMarkdown(documents: GeneratedDocuments, projectName: string): string {
  const sections: string[] = [];
  const divider = '\n\n---\n\n';

  if (documents.masterContext) {
    sections.push(`# ${documents.masterContext.title}\n\n${documents.masterContext.content}`);
  }

  if (documents.agentPRDs.length > 0) {
    sections.push(
      documents.agentPRDs.
      map((doc) => `# ${doc.title}\n\n${doc.content}`).
      join(divider)
    );
  }

  if (documents.collaborationMap) {
    sections.push(`# ${documents.collaborationMap.title}\n\n${documents.collaborationMap.content}`);
  }

  if (documents.setupGuide) {
    sections.push(`# ${documents.setupGuide.title}\n\n${documents.setupGuide.content}`);
  }

  return `# ${projectName} - PRD Package\n\nGenerated by AppArchitect\n\n${divider}${sections.join(divider)}`;
}

function downloadFileLocal(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function generateDocxContent(markdown: string): string {
  // Convert markdown to simple HTML for DOCX
  const html = markdown.
  replace(/^### (.+)$/gm, '<h3>$1</h3>').
  replace(/^## (.+)$/gm, '<h2>$1</h2>').
  replace(/^# (.+)$/gm, '<h1>$1</h1>').
  replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').
  replace(/\*(.+?)\*/g, '<em>$1</em>').
  replace(/`(.+?)`/g, '<code>$1</code>').
  replace(/^- (.+)$/gm, '<li>$1</li>').
  replace(/^\u2022 (.+)$/gm, '<li>$1</li>').
  replace(/^\u2713 (.+)$/gm, '<li>✓ $1</li>').
  replace(/^\u2717 (.+)$/gm, '<li>✗ $1</li>').
  replace(/^\u2610 (.+)$/gm, '<li>☐ $1</li>').
  replace(/\n{2,}/g, '</p><p>').
  replace(/\n/g, '<br/>');

  // Create a Word-compatible HTML document
  return `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head>
<meta charset="utf-8">
<style>
body { font-family: 'Courier New', monospace; font-size: 11pt; line-height: 1.6; color: #333; }
h1 { font-family: Arial, sans-serif; font-size: 24pt; color: #000; border-bottom: 2px solid #00E5CC; padding-bottom: 8pt; }
h2 { font-family: Arial, sans-serif; font-size: 18pt; color: #333; margin-top: 20pt; }
h3 { font-family: Arial, sans-serif; font-size: 14pt; color: #555; }
code { background: #f4f4f4; padding: 2pt 4pt; font-family: 'Courier New', monospace; }
pre { background: #f4f4f4; padding: 10pt; overflow-x: auto; }
li { margin: 4pt 0; }
</style>
</head>
<body><p>${html}</p></body>
</html>`;
}

export function ExportMenu({ documents, projectName = 'AppArchitect-PRD', v2Suite, validationScore }: ExportMenuProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isExporting, setIsExporting] = useState<ExportFormat | null>(null);
  const [lastExportResult, setLastExportResult] = useState<{format: string;success: boolean;} | null>(null);

  const hasDocuments =
  documents.masterContext ||
  documents.agentPRDs.length > 0 ||
  documents.collaborationMap ||
  documents.setupGuide;

  if (!hasDocuments) return null;

  const handleExport = async (format: ExportFormat) => {
    setIsExporting(format);
    setIsOpen(false);
    setLastExportResult(null);

    const safeFilename = projectName.replace(/[^a-zA-Z0-9-_]/g, '_');

    try {
      await new Promise((r) => setTimeout(r, 300)); // Brief delay for UX

      // Use V2 export if suite is available
      if (v2Suite && (format === 'markdown' || format === 'json' || format === 'html')) {
        const result = exportSuite(v2Suite, {
          format: format as V2ExportFormat,
          includeValidation: true,
          includeTableOfContents: true,
          projectName
        });

        if (result.success && result.files.length > 0) {
          downloadFile(result.files[0]);
          setLastExportResult({ format, success: true });
        }
        return;
      }

      // Legacy export path
      const markdown = getAllDocumentsMarkdown(documents, projectName);

      switch (format) {
        case 'markdown':
          downloadFileLegacy(markdown, `${safeFilename}.md`, 'text/markdown');
          break;

        case 'json':{
            // Convert legacy to V2 and export
            const suite = convertFromLegacyFormat(documents, projectName);
            const result = exportSuite(suite, {
              format: 'json',
              includeValidation: false,
              projectName
            });
            if (result.success && result.files.length > 0) {
              downloadFile(result.files[0]);
            }
            break;
          }

        case 'html':{
            const suite = convertFromLegacyFormat(documents, projectName);
            const result = exportSuite(suite, {
              format: 'html',
              includeValidation: false,
              projectName
            });
            if (result.success && result.files.length > 0) {
              downloadFile(result.files[0]);
            }
            break;
          }

        case 'pdf':{
            // Create a printable window for PDF export
            const printWindow = window.open('', '_blank');
            if (printWindow) {
              const html = generateDocxContent(markdown);
              printWindow.document.write(`
							<!DOCTYPE html>
							<html>
							<head>
								<title>${projectName}</title>
								<style>
									body { font-family: 'Courier New', monospace; font-size: 10pt; line-height: 1.5; max-width: 800px; margin: 0 auto; padding: 40px; }
									h1 { font-family: Arial, sans-serif; font-size: 20pt; border-bottom: 2px solid #00E5CC; padding-bottom: 8px; }
									h2 { font-family: Arial, sans-serif; font-size: 16pt; margin-top: 24px; }
									h3 { font-family: Arial, sans-serif; font-size: 12pt; }
									pre { white-space: pre-wrap; word-wrap: break-word; background: #f5f5f5; padding: 12px; }
									@media print { body { padding: 0; } }
								</style>
							</head>
							<body><pre style="white-space: pre-wrap;">${markdown}</pre></body>
							</html>
						`);
              printWindow.document.close();
              setTimeout(() => {
                printWindow.print();
              }, 250);
            }
            break;
          }

        case 'docx':{
            const docxHtml = generateDocxContent(markdown);
            const blob = new Blob(
              ['\ufeff', docxHtml], // BOM for proper encoding
              { type: 'application/msword' }
            );
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `${safeFilename}.doc`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
            break;
          }
      }

      setLastExportResult({ format, success: true });
    } catch (err) {
      console.error('Export failed:', err);
      setLastExportResult({ format, success: false });
    } finally {
      setIsExporting(null);
    }
  };

  // Legacy download helper (for non-V2 paths)
  function downloadFileLegacy(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  return (
    <div data-ev-id="ev_ac466ddf51" className="relative">
			<Button
        variant="secondary"
        size="sm"
        onClick={() => setIsOpen(!isOpen)}
        disabled={isExporting !== null}>

				{isExporting ?
        <Loader2 className="w-3 h-3 mr-1 animate-spin" /> :

        <Download className="w-3 h-3 mr-1" />
        }
				Export
				<ChevronDown className="w-3 h-3 ml-1" />
			</Button>

			{isOpen &&
      <>
					<div data-ev-id="ev_c3feb305a0" className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
					<div data-ev-id="ev_37f0b224d6" className="absolute right-0 top-full mt-2 w-56 bg-panel border border-border rounded-md shadow-xl z-50 overflow-hidden">
						<div data-ev-id="ev_56ef3761bc" className="px-3 py-2 border-b border-border">
							<span data-ev-id="ev_8219d60176" className="font-mono text-[9px] uppercase tracking-[2px] text-text-slate">
								Export Format
							</span>
						</div>
						<div data-ev-id="ev_b6d2ad608d" className="py-1">
							<button data-ev-id="ev_891095d125"
            onClick={() => handleExport('markdown')}
            className="w-full px-3 py-2 flex items-center gap-3 hover:bg-surface transition-colors text-left">

								<FileText className="w-4 h-4 text-cyan" />
								<div data-ev-id="ev_ef5217e3bb">
									<p data-ev-id="ev_1890a65ed6" className="font-mono text-[11px] text-text-white">Markdown</p>
									<p data-ev-id="ev_164d18a442" className="font-mono text-[9px] text-text-slate">.md file - raw text format</p>
								</div>
							</button>

							<button data-ev-id="ev_bc0fcc4e58"
            onClick={() => handleExport('pdf')}
            className="w-full px-3 py-2 flex items-center gap-3 hover:bg-surface transition-colors text-left">

								<FileDown className="w-4 h-4 text-signal-red" />
								<div data-ev-id="ev_09a32a0098">
									<p data-ev-id="ev_6aedc075ee" className="font-mono text-[11px] text-text-white">PDF</p>
									<p data-ev-id="ev_b01d0543b9" className="font-mono text-[9px] text-text-slate">Print dialog - save as PDF</p>
								</div>
							</button>

							<button data-ev-id="ev_15db44d1a8"
            onClick={() => handleExport('docx')}
            className="w-full px-3 py-2 flex items-center gap-3 hover:bg-surface transition-colors text-left">

								<File className="w-4 h-4 text-agent-backend" />
								<div data-ev-id="ev_98ed58121c">
									<p data-ev-id="ev_ff6451e2cf" className="font-mono text-[11px] text-text-white">Word Document</p>
									<p data-ev-id="ev_26499df6ce" className="font-mono text-[9px] text-text-slate">.doc file - editable format</p>
								</div>
							</button>

							<div data-ev-id="ev_0292ea7976" className="border-t border-border my-1" />
							<div data-ev-id="ev_d71c9ea5c8" className="px-3 py-1">
								<span data-ev-id="ev_b7d37dac35" className="font-mono text-[9px] uppercase tracking-[2px] text-text-slate">
									V2 Formats
								</span>
							</div>

							<button data-ev-id="ev_9ca0ab48ed"
            onClick={() => handleExport('json')}
            className="w-full px-3 py-2 flex items-center gap-3 hover:bg-surface transition-colors text-left">
								<FileText className="w-4 h-4 text-signal-yellow" />
								<div data-ev-id="ev_65f93145bf">
									<p data-ev-id="ev_c81727ed5e" className="font-mono text-[11px] text-text-white">JSON</p>
									<p data-ev-id="ev_75774949f3" className="font-mono text-[9px] text-text-slate">.json - structured data</p>
								</div>
							</button>

							<button data-ev-id="ev_0c8c7f6c03"
            onClick={() => handleExport('html')}
            className="w-full px-3 py-2 flex items-center gap-3 hover:bg-surface transition-colors text-left">
								<FileDown className="w-4 h-4 text-agent-frontend" />
								<div data-ev-id="ev_9ad4526845">
									<p data-ev-id="ev_99901baa86" className="font-mono text-[11px] text-text-white">HTML</p>
									<p data-ev-id="ev_9f7051475a" className="font-mono text-[9px] text-text-slate">.html - styled document</p>
								</div>
							</button>

							{validationScore !== undefined &&
            <div data-ev-id="ev_64cd5589ac" className="px-3 py-2 border-t border-border flex items-center gap-2">
									{validationScore >= 80 ?
              <CheckCircle className="w-3 h-3 text-signal-green" /> :

              <AlertCircle className="w-3 h-3 text-signal-yellow" />
              }
									<span data-ev-id="ev_d091a2cbbc" className="font-mono text-[9px] text-text-slate">
										Validation: {validationScore}/100
									</span>
								</div>
            }
						</div>
					</div>
				</>
      }
		</div>);

}